server {
    listen 80;
    listen [::]:80;

    server_name gslib2.h19h19.com;
    root /volume1/web/gslib2/current;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:glb|json)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name gslib2.h19h19.com;
    root /volume1/web/gslib2/current;
    index index.html;
    charset utf-8;

    include /usr/syno/etc/www/certificate/ReverseProxy_7c5662ba-6f08-432e-aecd-af210df42b5a/cert.conf*;
    include /usr/syno/etc/security-profile/tls-profile/config/ReverseProxy_7c5662ba-6f08-432e-aecd-af210df42b5a.conf*;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:glb|json)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }
}
