server {
    listen 80;
    listen [::]:80;

    server_name gslib2.h19h19.com;
    root /volume1/web/gslib2/current;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:glb|json)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=3600";
    }
}
