"""Browser smoke tests. In a Linux headless environment, run: xvfb-run -a python source/test_browser.py"""
from playwright.sync_api import sync_playwright
from pathlib import Path
import json, math, os
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'qa'; OUT.mkdir(exist_ok=True)
report={'checks':[],'errors':[],'external_requests':[],'method':'Chromium + Playwright; single-file HTML loaded directly into document. Container policy blocks file:// navigation; Xvfb provides graphics display.'}
def ok(name, condition=True):
 assert condition,name
 report['checks'].append(name);print('PASS',name,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
 context=browser.new_context(viewport={'width':1600,'height':1000},device_scale_factor=1,accept_downloads=True,offline=True)
 page=context.new_page()
 page.on('pageerror',lambda e:report['errors'].append(str(e)))
 page.on('request',lambda r:report['external_requests'].append(r.url) if r.url.startswith(('http:','https:')) else None)
 page.set_content((ROOT/'Gayang_Library_3D.html').read_text(),wait_until='load',timeout=120000)
 page.wait_for_function('window.__viewerReady || window.__viewerError',timeout=60000)
 ok('Actual WebGL2 initialized',page.evaluate('!!window.__viewerReady && !window.__viewerError'))
 page.wait_for_timeout(650)
 ok('Initial inside floor view',page.evaluate("__test.state.mode==='floor' && __test.state.floor===1 && __test.state.cut"))
 ok('3D mesh count and spaces',page.evaluate('__test.stats.meshes > 100 && __test.rooms.length > 40'))
 page.screenshot(path=str(OUT/'inside_2F.png'))
 # Orbit controls must change actual camera state.
 before=page.evaluate('({...__test.orbit})')
 page.mouse.move(1030,580);page.mouse.down();page.mouse.move(1100,600,steps=6);page.mouse.up()
 ok('Mouse drag rotates actual camera',abs(page.evaluate('__test.orbit.yaw')-before['yaw'])>.1)
 d=page.evaluate('__test.orbit.distance');page.mouse.wheel(0,-100);page.wait_for_timeout(150)
 ok('Wheel zoom changes camera distance',page.evaluate('__test.orbit.distance')<d)
 t=page.evaluate('[...__test.orbit.target]');page.mouse.move(1030,580);page.mouse.down(button='right');page.mouse.move(1070,580,steps=3);page.mouse.up(button='right')
 ok('Right drag pans camera',page.evaluate('__test.orbit.target')!=t)
 page.locator('#reset-view').click();page.wait_for_timeout(200)
 # All six real levels have meshes.
 for f in [-1,0,1,2,3,4]:
  page.locator(f'.floor-tabs [data-floor="{f}"]').click();page.wait_for_timeout(250)
  levels=page.evaluate('[...new Set(__test.getVisible().map(m=>m.level))]')
  ok(f'Floor {f} isolates correct geometry',levels==[f])
  if f in [-1,0,2,3,4]:page.screenshot(path=str(OUT/f'floor_{f}.png'))
 # Rooms, zooming and interior movement.
 page.locator('.floor-tabs [data-floor="1"]').click()
 page.locator('#room-search').fill('시민강의실')
 ok('Room search filters real rooms',page.locator('.room-row').count()==1)
 page.locator('.room-row').click();page.wait_for_timeout(200)
 ok('Room selection and inspector work',page.locator('#selected-name').inner_text()=='시민강의실' and page.locator('#room-detail').is_visible())
 page.screenshot(path=str(OUT/'selected_room.png'))
 page.locator('#walk-room').click();page.wait_for_timeout(400)
 ok('First-person mode activates',page.evaluate('__test.state.walk'))
 pos=page.evaluate('[...__test.walk.eye]');page.locator('#viewport').focus();page.keyboard.down('w');page.wait_for_timeout(450);page.keyboard.up('w')
 now=page.evaluate('[...__test.walk.eye]');ok('W key moves first-person camera',math.dist(pos,now)>.15)
 page.screenshot(path=str(OUT/'interior_walk.png'))
 page.keyboard.press('Escape');ok('Escape exits first-person',not page.evaluate('__test.state.walk'))
 page.locator('#room-search').fill('')
 page.locator('#toggle-furniture').uncheck();ok('Furniture toggle changes geometry visibility',page.evaluate("!__test.getVisible().some(m=>m.layer==='furniture')"))
 page.locator('#toggle-furniture').check()
 page.locator('#toggle-mep').check();ok('MEP layer can be displayed',page.evaluate("__test.getVisible().some(m=>m.layer==='mep')"))
 page.locator('#toggle-mep').uncheck()
 page.locator('#wall-height').evaluate("e=>e.value='0.60'");page.locator('#wall-height').dispatch_event('input');ok('Wall cut slider changes clipping',page.evaluate('__test.state.wallHeight===.6'))
 page.locator('#wall-height').evaluate("e=>e.value='1.45'");page.locator('#wall-height').dispatch_event('input')
 # Source drawings are actually embedded and loaded.
 page.locator('#source-open').click();page.wait_for_timeout(250)
 ok('Embedded original PDF page displayed',page.evaluate('document.getElementById("source-img").naturalWidth>1000'))
 page.locator('#source-select').select_option('civil');page.wait_for_timeout(150)
 ok('Civil drawing available',page.locator('#source-caption').inner_text().endswith('토목 PDF 16쪽.'))
 page.locator('#source-select').select_option('landscape');page.wait_for_timeout(150)
 page.screenshot(path=str(OUT/'original_drawing.png'))
 page.locator('[data-close="source-dialog"]').click()
 # Model-wide modes.
 page.locator('[data-mode="overview"]').click();page.wait_for_timeout(450)
 ok('Overview includes building and site',page.evaluate("__test.getVisible().some(m=>m.level===9) && __test.getVisible().some(m=>m.level===4)"))
 page.screenshot(path=str(OUT/'exterior.png'))
 page.locator('details summary').click();page.locator('#toggle-roof').uncheck()
 ok('Roof can be hidden from overview',page.evaluate('!__test.getVisible().some(m=>m.level===4)'))
 page.locator('details summary').click()
 page.locator('[data-mode="explode"]').click();page.wait_for_timeout(500)
 ok('Exploded view includes all occupied floors',page.evaluate('[-1,0,1,2,3].every(l=>__test.getVisible().some(m=>m.level===l))'))
 page.screenshot(path=str(OUT/'exploded.png'))
 page.locator('[data-mode="section"]').click();page.locator('#slice-axis').select_option('z');page.locator('#slice-value').evaluate("e=>e.value='60'");page.locator('#slice-value').dispatch_event('input');page.wait_for_timeout(500)
 ok('Section axis and plane are adjustable',page.evaluate("__test.state.axis==='z' && __test.state.slice===60"))
 page.screenshot(path=str(OUT/'section.png'))
 # Model export has a real GLB header, not an image or text file.
 with page.expect_download(timeout=15000) as dw:page.locator('#download-glb').click()
 dw.value.save_as(str(OUT/'export_test.glb'));ok('GLB download is valid binary', (OUT/'export_test.glb').read_bytes()[:4]==b'glTF')
 with page.expect_download(timeout=15000) as dw:page.locator('#save-image').click()
 dw.value.save_as(str(OUT/'export_view.png'));ok('3D screenshot export works',(OUT/'export_view.png').read_bytes()[:8]==b'\x89PNG\r\n\x1a\n')
 page.locator('#help-open').click();ok('Usage and accuracy notes accessible',page.locator('#help-dialog').is_visible());page.locator('[data-close="help-dialog"]').click()
 page.locator('[data-mode="floor"]').click();page.locator('.floor-tabs [data-floor="1"]').click()
 page.set_viewport_size({'width':1366,'height':768});page.locator('#reset-view').click();page.wait_for_timeout(250);page.screenshot(path=str(OUT/'laptop.png'))
 ok('Laptop layout no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(350);page.locator('#reset-view').click();page.wait_for_timeout(450)
 ok('Mobile layout no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 page.screenshot(path=str(OUT/'mobile.png'))
 page.locator('.mobile-floors [data-floor="0"]').click();ok('Mobile floor controls work',page.evaluate('__test.state.floor===0'))
 page.locator('#menu-toggle').click();ok('Mobile settings drawer opens',page.locator('#sidebar').evaluate('(e)=>e.classList.contains("mobile-open")'));page.locator('#menu-toggle').click()
 ok('No JavaScript runtime errors',not report['errors']);ok('No external network requests',not report['external_requests'])
 ok('WebGL error state is clear',page.evaluate('__test.getGL().error===0'))
 browser.close()
(ROOT/'qa'/'test_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print('TOTAL',len(report['checks']),'checks passed')
