"""Functional regression of the integrated, offline Gayang viewer (Playwright)."""
from playwright.sync_api import sync_playwright
from pathlib import Path
import json,math,os,sys,hashlib
import tempfile
SITE=Path(__file__).resolve().parent.parent; OUT=Path(tempfile.mkdtemp(prefix='gayang-qa-'))
report={'checks':[],'errors':[],'console_errors':[],'external_requests':[], 'method':'Browser plugin absent; Playwright + headed Chromium under Xvfb. Offline set_content (container policy blocks file://).', 'viewports':['1600x1000','1366x768','390x844'], 'untested':['Safari, Firefox, physical touch devices','Full-screen API (container enterprise policy disables fullscreen)','Wall collision and automatic stair stepping are not implemented']}
def ok(name, cond=True):
 if not cond: raise AssertionError(name)
 report['checks'].append(name); print('PASS',name,flush=True)
try:
 with sync_playwright() as p:
  b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=False,args=['--no-sandbox','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
  c=b.new_context(viewport={'width':1600,'height':1000},device_scale_factor=1,offline=True,accept_downloads=True)
  page=c.new_page();page.on('pageerror',lambda e:report['errors'].append(str(e)))
  page.on('console',lambda m:report['console_errors'].append(m.text) if m.type=='error' else None)
  page.on('request',lambda r:report['external_requests'].append(r.url) if r.url.startswith(('http:','https:')) else None)
  page.set_content((SITE/'index.html').read_text(),wait_until='load',timeout=120000)
  page.wait_for_function('window.__viewerReady || window.__viewerError',timeout=45000)
  ok('WebGL2 initialized',page.evaluate('!!__viewerReady && !window.__viewerError'))
  ok('Correct page title and nonempty app', '가양관' in page.title() and page.locator('#video-landmarks button').count()==6)
  page.wait_for_timeout(500)
  ok('Initial 1F stair first-person view',page.evaluate("__test.state.walk && __test.state.floor===0 && __test.state.landmark==='tiers'"))
  ok('Merged mesh/room data',page.evaluate('__test.stats.meshes>=240 && __test.rooms.length===66'))
  ok('No loading/error overlay',page.locator('#loading').evaluate("e=>e.classList.contains('gone')") and page.locator('.load-error').count()==0)
  page.screenshot(animations='disabled',path=str(OUT/'final_stairs.png'))
  for key in ['tiers','shelves','carrels','desk','stairwell','reading']:
   page.locator(f'[data-landmark="{key}"]').click(); page.wait_for_timeout(80)
   ok(f'Landmark {key} updates first-person camera',page.evaluate(f"__test.state.landmark==='{key}' && __test.state.walk && __test.state.floor===0"))
   if not page.locator('#reference-panel').is_visible():page.locator('#compare-open').click()
   page.wait_for_function("document.getElementById('reference-img').naturalWidth>400")
   ok(f'Landmark {key} has embedded source and inference notes',page.locator('#reference-inferred').inner_text()!='' and page.locator('#reference-seen').inner_text()!='')
   if key=='tiers':page.screenshot(animations='disabled',path=str(OUT/'final_comparison.png'))
   if key=='reading':ok('Unknown reading room position explicitly disclosed','임시 배치' in page.locator('#reference-inferred').inner_text())
   page.locator('#reference-close').click()
   if key in ['shelves','carrels','desk','stairwell','reading']:page.screenshot(animations='disabled',path=str(OUT/f'final_{key}.png'))
  page.locator('[data-landmark="tiers"]').click()
  yaw=page.evaluate('__test.walk.yaw');page.mouse.move(960,590);page.mouse.down();page.mouse.move(1050,600,steps=5);page.mouse.up()
  ok('Mouse look changes first-person yaw',abs(page.evaluate('__test.walk.yaw')-yaw)>.1)
  pos=page.evaluate('[...__test.walk.eye]');page.keyboard.down('w');page.wait_for_function('p=>Math.hypot(...__test.walk.eye.map((x,i)=>x-p[i]))>.1',arg=pos,timeout=10000);page.keyboard.up('w')
  ok('W moves first-person position',math.dist(pos,page.evaluate('[...__test.walk.eye]'))>.1)
  y=page.evaluate('__test.walk.eye[1]');page.keyboard.down('r');page.wait_for_function('y=>__test.walk.eye[1]>y+.01',arg=y,timeout=10000);page.keyboard.up('r')
  ok('R increases first-person height',page.evaluate('__test.walk.eye[1]')>y)
  y=page.evaluate('__test.walk.eye[1]');page.keyboard.down('f');page.wait_for_function('y=>__test.walk.eye[1]<y-.01',arg=y,timeout=10000);page.keyboard.up('f')
  ok('F decreases first-person height',page.evaluate('__test.walk.eye[1]')<y)
  page.locator('#toggle-videoCeiling').uncheck()
  ok('Ceiling control hides video ceiling and lights',page.evaluate("!__test.getVisible().some(x=>['videoCeiling','videoLights'].includes(x.layer))"))
  page.locator('#toggle-videoCeiling').check()
  ok('Ceiling control restores real ceiling geometry',page.evaluate("__test.getVisible().some(x=>x.layer==='videoCeiling')"))
  page.keyboard.press('Escape');ok('Escape returns to orbit mode',not page.evaluate('__test.state.walk'))
  page.locator('#video-cutaway').click();page.wait_for_timeout(150)
  ok('1F cutaway keeps observed stairs and furniture',page.evaluate("__test.getVisible().some(x=>x.layer==='videoBuilt') && __test.getVisible().some(x=>x.layer==='videoFurniture')"))
  page.screenshot(animations='disabled',path=str(OUT/'final_cutaway.png'))
  yaw=page.evaluate('__test.orbit.yaw');page.mouse.move(960,590);page.mouse.down();page.mouse.move(1040,595,steps=6);page.mouse.up()
  ok('Mouse drag rotates model',abs(page.evaluate('__test.orbit.yaw')-yaw)>.1)
  d=page.evaluate('__test.orbit.distance');page.mouse.wheel(0,-140);page.wait_for_timeout(150)
  ok('Wheel zoom changes camera distance',page.evaluate('__test.orbit.distance')<d)
  t=page.evaluate('[...__test.orbit.target]');page.mouse.move(960,590);page.mouse.down(button='right');page.mouse.move(1040,590,steps=5);page.mouse.up(button='right')
  ok('Right drag pans model',page.evaluate('__test.orbit.target')!=t)
  page.locator('#rotate-auto').click();yaw=page.evaluate('__test.orbit.yaw');page.wait_for_function('y=>__test.orbit.yaw!==y',arg=yaw,timeout=10000)
  ok('Auto-rotation advances camera',page.evaluate('__test.orbit.yaw')!=yaw);page.locator('#rotate-auto').click()
  for f in [-1,0,1,2,3,4]:
   page.locator(f'.floor-tabs [data-floor="{f}"]').click();page.wait_for_timeout(80)
   ok(f'Floor {f} isolates real model level',page.evaluate('[...new Set(__test.getVisible().map(m=>m.level))]')==[f])
  page.locator('.floor-tabs [data-floor="1"]').click();page.locator('#room-search').fill('시민강의실')
  ok('Room search filters original rooms',page.locator('.room-row').count()==1)
  page.locator('.room-row').click();ok('Room inspector still works',page.locator('#selected-name').inner_text()=='시민강의실' and page.locator('#room-detail').is_visible())
  page.locator('#walk-room').click();ok('Original 2F room first-person preserved',page.evaluate('__test.state.floor===1 && __test.state.walk'))
  page.keyboard.press('Escape');page.locator('#room-search').fill('');page.locator('.floor-tabs [data-floor="0"]').click()
  page.locator('#toggle-furniture').uncheck()
  ok('Furniture control hides old and new furniture',page.evaluate("!__test.getVisible().some(x=>['videoFurniture','furniture'].includes(x.layer))"))
  page.locator('#toggle-furniture').check()
  page.locator('#toggle-mep').check();ok('Original mechanical equipment layer preserved',page.evaluate("__test.getVisible().some(x=>x.layer==='mep')"));page.locator('#toggle-mep').uncheck()
  page.locator('#wall-height').evaluate("e=>e.value='0.65'");page.locator('#wall-height').dispatch_event('input')
  ok('Wall cut height changes actual clip plane',page.evaluate("Math.abs(__test.clip({level:0,layer:'videoWall'})[0]-.65)<1e-6"))
  ok('Video glazing follows wall cut',page.evaluate("Math.abs(__test.clip({level:0,layer:'videoGlass'})[0]-.65)<1e-6"))
  ok('Tiered seats are not removed by wall cut',page.evaluate("__test.clip({level:0,layer:'videoBuilt'})[0]===100000"))
  page.locator('.system-controls summary').click()
  for layer in ['power','comm','fire','plumbing','hvacpipe']:
   page.locator('#toggle-'+layer).check()
   ok(f'{layer} checkbox enables actual geometry',page.evaluate(f"__test.getVisible().some(x=>x.layer==='{layer}')"))
   ok(f'{layer} above-ceiling paths not wrongly wall-clipped',page.evaluate(f"__test.clip({{level:0,layer:'{layer}'}})[0]===100000"))
   page.locator('#toggle-'+layer).uncheck()
   ok(f'{layer} checkbox hides actual geometry',page.evaluate(f"!__test.getVisible().some(x=>x.layer==='{layer}')"))
  for layer in ['power','comm','fire','plumbing','hvacpipe']:page.locator('#toggle-'+layer).check()
  ok('Unverified MEP status visible',page.locator('#system-warning').is_visible())
  page.locator('#systems-off').click();ok('All systems off button works',not page.locator('#system-warning').is_visible())
  page.locator('.system-controls summary').click()
  page.locator('#source-open').click();page.wait_for_function("document.getElementById('source-img').naturalWidth>1000")
  ok('Original floor drawing still available',page.locator('#source-dialog').is_visible())
  for source in ['civil','landscape','video-tiers','video-desk','video-reading']:
   page.locator('#source-select').select_option(source);page.wait_for_timeout(70)
   ok(f'Source {source} decodes',page.evaluate("document.getElementById('source-img').naturalWidth>400"))
  page.locator('#source-zoom').evaluate("e=>e.value='160'");page.locator('#source-zoom').dispatch_event('input')
  ok('Source image zoom works',page.locator('#source-img').evaluate("e=>e.style.width==='160%'"))
  page.locator('[data-close="source-dialog"]').click()
  page.locator('[data-mode="overview"]').click();page.wait_for_timeout(150)
  ok('Whole building and original site preserved',page.evaluate("__test.getVisible().some(x=>x.level===9)&&__test.getVisible().some(x=>x.level===4)"))
  page.screenshot(animations='disabled',path=str(OUT/'final_whole_building.png'))
  page.locator('[data-mode="explode"]').click();page.wait_for_timeout(150)
  ok('Exploded view contains all occupied floors',page.evaluate('[-1,0,1,2,3].every(l=>__test.getVisible().some(m=>m.level===l))'))
  page.locator('#explode-height').evaluate("e=>e.value='7'");page.locator('#explode-height').dispatch_event('input')
  ok('Explode distance drives actual offsets',page.evaluate('__test.offset({level:2})===21 && __test.offset({level:9})===0'))
  page.screenshot(animations='disabled',path=str(OUT/'final_exploded.png'))
  page.locator('[data-mode="section"]').click()
  for axis,idx in [('x',1),('y',2),('z',3)]:
   page.locator('#slice-axis').select_option(axis);page.locator('#slice-value').evaluate("e=>e.value='55'");page.locator('#slice-value').dispatch_event('input')
   ok(f'Section {axis} cuts both architecture and new features',page.evaluate(f"__test.clip({{level:0,layer:'videoBuilt'}})[1]==={idx} && __test.clip({{level:0,layer:'fire'}})[1]==={idx}"))
  page.wait_for_timeout(150);page.screenshot(animations='disabled',path=str(OUT/'final_section.png'))
  for btn,field in [('top-view','pitch'),('front-view','pitch'),('iso-view','yaw')]:
   page.locator('#'+btn).click();ok(f'Camera preset {btn} responds',math.isfinite(page.evaluate('__test.orbit.'+field)))
  with page.expect_download(timeout=15000) as dl:page.locator('#download-glb').click()
  dl.value.save_as(str(OUT/'export_test.glb'))
  ok('GLB export bytes match integrated model',(OUT/'export_test.glb').read_bytes()==(SITE/'Gayang_Library_Video.glb').read_bytes())
  with page.expect_download(timeout=15000) as dl:page.locator('#save-image').click()
  dl.value.save_as(str(OUT/'export_test.png'))
  ok('Current 3D render exports as PNG',(OUT/'export_test.png').read_bytes()[:8]==b'\x89PNG\r\n\x1a\n')
  page.locator('#help-open').click();ok('Help lists measurement and walking limitations', '벽 충돌' in page.locator('#help-dialog').inner_text() and '영상' in page.locator('#help-dialog').inner_text());page.locator('[data-close="help-dialog"]').click()
  page.locator('[data-landmark="tiers"]').click()
  page.set_viewport_size({'width':1366,'height':768});page.wait_for_timeout(300)
  page.screenshot(animations='disabled',path=str(OUT/'final_laptop.png'));ok('Laptop document has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(4500)
  page.screenshot(animations='disabled',path=str(OUT/'final_mobile.png'));ok('Mobile document has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  page.locator('#menu-toggle').click();ok('Mobile settings drawer opens',page.locator('#sidebar').evaluate("e=>e.classList.contains('mobile-open')"));page.screenshot(animations='disabled',path=str(OUT/'final_mobile_drawer.png'))
  page.locator('[data-landmark="shelves"]').click();ok('Mobile landmark navigates and closes drawer',page.evaluate("__test.state.landmark==='shelves'") and page.locator('#sidebar').evaluate("e=>!e.classList.contains('mobile-open')"))
  page.locator('#compare-open').click();ok('Mobile source comparison visible',page.locator('#reference-panel').is_visible());page.screenshot(animations='disabled',path=str(OUT/'final_mobile_comparison.png'));page.locator('#reference-close').click()
  pos=page.evaluate('[...__test.walk.eye]');btn=page.locator('[data-key="w"]').bounding_box();page.mouse.move(btn['x']+btn['width']/2,btn['y']+btn['height']/2);page.mouse.down();page.wait_for_function('p=>Math.hypot(...__test.walk.eye.map((x,i)=>x-p[i]))>.05',arg=pos,timeout=10000);page.mouse.up()
  ok('Onscreen walking controls move camera',math.dist(pos,page.evaluate('[...__test.walk.eye]'))>.05)
  page.locator('.mobile-floors [data-floor="2"]').click();ok('Mobile floor navigation works',page.evaluate('__test.state.floor===2 && !__test.state.walk'))
  ok('No JavaScript runtime errors',not report['errors']);ok('No unexpected console errors',not report['console_errors']);ok('No external network traffic',not report['external_requests']);ok('WebGL error state clear',page.evaluate('__test.getGL().error===0'))
  report['passed']=True;report['count']=len(report['checks']);b.close()
except Exception as exc:
 report['passed']=False;report['failure']=str(exc);report['count']=len(report['checks']);raise
finally:
 (OUT/'test_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
 print('TOTAL',report['count'],'passed; result',report['passed'],flush=True)
